### ISSUE TITLE
В окно ответа можно ввести знаки сравнения, хотя ответ подразумевает вводить только числа

### ISSUE THREAD

**Issue by Ge0rginv** [Last-Week-End/TestApplication#4]
описание программа даёт вводить некорректные значения 

![Снимок экрана 2024-12-17 160448](https://github.com/user-attachments/assets/f06a8ec3-a0bf-4d2b-a815-e7dcc33b91df)
ожидаемое поведение : программа не даст ввести символы "  <, > ,="

**Comment by Last-Week-End** [comment]
Введен неверный ответ. Программа сообщает, что ответ не верный. Здесь нет ошибки.
